### ISSUE TITLE
[1.12][Bug] Spiders struggle when surrounded by blocks that have irregular hitboxes, such as fences.

### ISSUE THREAD

**Issue by SandwichHorror** [TheCyberBrick/Spiders-2.0#15]
I deliberately set up a weird pattern of fences to see if I could bork the climbing AI, and unfortunately I succeeded. When stuck between a few fences with a fence directly above, the spider began turning around and around on itself. As far as I could tell, it wasn't spinning (like with invalid pathing), but simply glitching out due to attempting to climb and not being able to deal with the weird fence hitboxes.
![2020-10-06_22 54 32](https://user-images.githubusercontent.com/59847281/95288970-b18d8f00-0837-11eb-8675-c08b3ce15133.png)
![2020-10-06_22 54 48](https://user-images.githubusercontent.com/59847281/95288985-b94d3380-0837-11eb-9f56-b67cd9e8ecd2.png)
![2020-10-06_22 55 38](https://user-images.githubusercontent.com/59847281/95289012-c4a05f00-0837-11eb-94bf-55cfbad2c834.png)

**Comment by TheCyberBrick** [comment]
Mhm, there are also some other situations where they get stuck e.g. in 1 block tall corridors. This is probably because the orientation of the spiders is purely reactive, i.e. it's based on the spider's position and doesn't depend on the previous orientation. I've already made some WIP code to address this, but it makes the orientation react slightly slower to the environment, so not yet sure whether I'm going to actually use it. May also be a problem with the pathfinder though.

**Comment by TheCyberBrick** [comment]
This has now been "fixed", i.e. the path finder no longer tries to path below the fences. However, due to the fence's bounding boxes the spider will still be unable to climb past something like this, because there's no contact between the fence and the roof.
