### ISSUE TITLE
[1.16.3][Bug] Spider Spawner

### ISSUE THREAD

**Issue by ElasticKnife** [TheCyberBrick/Spiders-2.0#22]
Spawners generate spiders at an incredible rate, with seemingly no cap, causing extreme lag as entities build up.

**Comment by Coraline77447** [comment]
I'm having this same exact issue cause I'd recently found a abandoned mineshaft by finding a ravine and wanted to put out the lava that was causing fires so when I went into creative mode, I then headed toward the fires and lava, that's when the cave spider spawner that was nearby started producing massive, massive amounts of cave spiders, I had to fly out of the area for them all to despawn, I then headed back to break the spawner and more spawned in so I then had to leave the area yet again for the freshly spawned in cave spiders to despawn again. Now I'll have to uninstall the mod temporarily till this issue gets fixed so that I and many other people who uses this mod wont lag completely out. Btw I was lucky that I was not in survival mode or else the lag and all of those cave spiders would've destroyed me and my enchanted leather armor. P.s Ik that everything that I said isnt important but I was gonna report this same exact issue myself but apparently someone has already beaten me to the punch 14 hours earlier and why I said all of this was so that you could experience what I had experienced and know what I'd experienced and now I'm bummed out now cause I need to uninstall this great mod till this issue gets fixed....

**Comment by ElasticKnife** [comment]
@Coraline77447 Don't worry, I read the whole thing lol.  Quick tip if running into this sort of issue again, is instead of leaving the area to despawn the spiders, just flick it to peaceful to clear the mobs and destroy the spawner, then switch back to previous setting.  Although, it sounds like you may be running a server with others, in which case that could be something you wanted avoid, hence why you didn't.

**Comment by BugmanBugman** [comment]
![2020-10-18_14 06 22](https://user-images.githubusercontent.com/40730042/96377576-0e4c4c00-114c-11eb-83d5-4ee3333efccb.png)
Got a screenshot of it in action, it's hilarious to watch the cave get flooded with spiders in a blink of an eye

**Comment by TheCyberBrick** [comment]
The issue of spawners spawning infinite spiders is now resolved for 1.15.2+
I'll need to find another workaround for 1.12.2 though.
